# ================================================================
# LUNAR IMAGE CORRESPONDENCE AND REGISTRATION SYSTEM
# Flask API / HTTP SERVER
# SIH26166 - Chandrayaan-2
#
# This file is intentionally kept lightweight at startup.
# The heavy AI backend is imported ONLY when /analyze is called.
# ================================================================

import os
import uuid
from pathlib import Path

from flask import Flask, request, jsonify, send_from_directory
from werkzeug.utils import secure_filename


# ================================================================
# APPLICATION PATHS
# ================================================================

BASE_DIR = Path(__file__).resolve().parent

UPLOAD_FOLDER = BASE_DIR / "uploads"
RESULTS_FOLDER = BASE_DIR / "lunar_results"

UPLOAD_FOLDER.mkdir(parents=True, exist_ok=True)
RESULTS_FOLDER.mkdir(parents=True, exist_ok=True)


# ================================================================
# FLASK CONFIGURATION
# ================================================================

app = Flask(__name__)

# Maximum combined request size accepted by Flask.
# Keep this below Render/proxy limits and avoid accidental huge uploads.
app.config["MAX_CONTENT_LENGTH"] = 100 * 1024 * 1024


# ================================================================
# ALLOWED FILE TYPES
# ================================================================

ALLOWED_EXTENSIONS = {
    "png",
    "jpg",
    "jpeg",
    "bmp",
    "tif",
    "tiff",
}


def allowed_file(filename):
    """Return True when the filename has a supported image extension."""
    if not filename or "." not in filename:
        return False

    extension = filename.rsplit(".", 1)[1].lower()
    return extension in ALLOWED_EXTENSIONS


# ================================================================
# CORS
# ================================================================
#
# GitHub Pages is a different origin from Render.
# The frontend sends multipart/form-data to /analyze, so the API
# explicitly allows cross-origin requests.
#
# CORS headers are also applied to error responses generated by Flask.
# ================================================================

@app.after_request
def add_cors_headers(response):
    response.headers["Access-Control-Allow-Origin"] = "*"
    response.headers["Access-Control-Allow-Methods"] = "GET, POST, OPTIONS"
    response.headers["Access-Control-Allow-Headers"] = "Content-Type"
    response.headers["Access-Control-Expose-Headers"] = "Content-Type"
    return response


# ================================================================
# HOME
# ================================================================

@app.route("/", methods=["GET"])
def home():
    return jsonify({
        "system": "Lunar Image Correspondence and Registration System",
        "problem_statement": "SIH26166",
        "status": "online",
        "backend": "LoFTR + RANSAC + Registration + Quality Analysis",
    })


# ================================================================
# HEALTH CHECK
# ================================================================

@app.route("/status", methods=["GET"])
def status():
    return jsonify({
        "flask": "online",
        "ai_backend": "available",
        "system": "Lunar Image Correspondence and Registration System",
        "pipeline": [
            "Image Acquisition",
            "Illumination-Robust Preprocessing",
            "Multi-Scale LoFTR",
            "Confidence Filtering",
            "RANSAC Verification",
            "Registration Refinement",
            "Spatial Analysis",
            "Quality Evaluation",
        ],
    })


# ================================================================
# OPTIONAL PREFLIGHT HANDLER
# ================================================================

@app.route("/analyze", methods=["OPTIONS"])
def analyze_options():
    """Handle browser CORS preflight requests."""
    return ("", 204)


# ================================================================
# MAIN AI ANALYSIS API
# ================================================================

@app.route("/analyze", methods=["POST"])
def analyze():
    """
    Receive two lunar images and run the AI registration pipeline.

    IMPORTANT:
    The heavy lunar_backend import happens INSIDE this function.
    This keeps Gunicorn/Flask startup lightweight and prevents the
    PyTorch/LoFTR stack from being loaded merely by starting the web
    server.
    """

    request_id = uuid.uuid4().hex[:8]

    image_A_path = None
    image_B_path = None

    print("\n" + "=" * 70)
    print("NEW LUNAR ANALYSIS REQUEST")
    print("Request ID:", request_id)
    print("=" * 70)

    try:
        # ------------------------------------------------------------
        # CHECK IMAGE A
        # ------------------------------------------------------------

        if "image_A" not in request.files:
            return jsonify({
                "success": False,
                "request_id": request_id,
                "error": "Reference Image A was not uploaded.",
            }), 400

        # ------------------------------------------------------------
        # CHECK IMAGE B
        # ------------------------------------------------------------

        if "image_B" not in request.files:
            return jsonify({
                "success": False,
                "request_id": request_id,
                "error": "Target Image B was not uploaded.",
            }), 400

        image_A = request.files["image_A"]
        image_B = request.files["image_B"]

        # ------------------------------------------------------------
        # CHECK FILENAMES
        # ------------------------------------------------------------

        if not image_A.filename:
            return jsonify({
                "success": False,
                "request_id": request_id,
                "error": "Image A has no filename.",
            }), 400

        if not image_B.filename:
            return jsonify({
                "success": False,
                "request_id": request_id,
                "error": "Image B has no filename.",
            }), 400

        # ------------------------------------------------------------
        # CHECK FILE TYPES
        # ------------------------------------------------------------

        if not allowed_file(image_A.filename):
            return jsonify({
                "success": False,
                "request_id": request_id,
                "error": "Unsupported Image A format.",
            }), 400

        if not allowed_file(image_B.filename):
            return jsonify({
                "success": False,
                "request_id": request_id,
                "error": "Unsupported Image B format.",
            }), 400

        # ------------------------------------------------------------
        # SANITIZE EXTENSIONS
        # ------------------------------------------------------------

        extension_A = Path(image_A.filename).suffix.lower()
        extension_B = Path(image_B.filename).suffix.lower()

        # The extension has already been checked against the allowlist.
        # UUID names prevent collisions and unsafe user-controlled paths.
        image_A_path = UPLOAD_FOLDER / f"image_A_{request_id}{extension_A}"
        image_B_path = UPLOAD_FOLDER / f"image_B_{request_id}{extension_B}"

        # ------------------------------------------------------------
        # SAVE UPLOADS
        # ------------------------------------------------------------

        image_A.save(str(image_A_path))
        image_B.save(str(image_B_path))

        print("Image A received:", image_A_path)
        print("Image B received:", image_B_path)

        # ------------------------------------------------------------
        # LAZY IMPORT OF HEAVY AI BACKEND
        # ------------------------------------------------------------
        #
        # DO NOT move this import to the top of this file.
        # PyTorch/Kornia/LoFTR should not be loaded during Gunicorn
        # startup.
        # ------------------------------------------------------------

        print("Loading AI backend...")

        from lunar_backend import analyze_lunar_images

        print("Starting AI processing...")

        # ------------------------------------------------------------
        # RUN AI PIPELINE
        # ------------------------------------------------------------

        results = analyze_lunar_images(
            str(image_A_path),
            str(image_B_path),
            output_folder=str(RESULTS_FOLDER),
        )

        # ------------------------------------------------------------
        # RESULT IMAGE URLS
        # ------------------------------------------------------------

        results["images"] = {
            "preprocessed_A": "/results/preprocessed_A.png",
            "preprocessed_B": "/results/preprocessed_B.png",
            "ransac_inliers": "/results/ransac_inliers.png",
            "registered_refined": "/results/registered_refined.png",
            "correspondence_quality_map":
                "/results/correspondence_quality_map.png",
            "spatial_distribution":
                "/results/spatial_distribution.png",
        }

        # ------------------------------------------------------------
        # FINAL RESPONSE
        # ------------------------------------------------------------

        response = {
            "success": True,
            "message": "Lunar image analysis completed successfully.",
            "request_id": request_id,
            "results": results,
        }

        print("AI analysis completed.")
        print("Results sent to frontend.")
        print("=" * 70)

        return jsonify(response), 200

    except MemoryError:
        # Python-level MemoryError. Note that an OS-level OOM kill can
        # terminate the whole process before Flask can reach this block.
        print("ERROR: Python reported insufficient memory.")

        return jsonify({
            "success": False,
            "request_id": request_id,
            "error": (
                "The AI analysis requires more memory than the server "
                "currently has available."
            ),
        }), 503

    except Exception as exc:
        print("ERROR during analysis:", repr(exc))

        return jsonify({
            "success": False,
            "request_id": request_id,
            "error": str(exc),
        }), 500

    finally:
        # Uploaded source files are temporary inputs. Remove them after
        # processing so repeated requests do not fill the Render disk.
        for uploaded_path in (image_A_path, image_B_path):
            if uploaded_path is not None:
                try:
                    Path(uploaded_path).unlink(missing_ok=True)
                except Exception as cleanup_error:
                    print(
                        "Warning: could not remove temporary upload:",
                        cleanup_error,
                    )


# ================================================================
# SERVE RESULT IMAGES
# ================================================================

@app.route("/results/<path:filename>", methods=["GET"])
def result_image(filename):
    """
    Serve generated result images.

    send_from_directory prevents the requested filename from being
    interpreted as an arbitrary filesystem path.
    """
    return send_from_directory(
        str(RESULTS_FOLDER),
        filename,
    )


# ================================================================
# SERVE UPLOADED IMAGES
# ================================================================

@app.route("/uploads/<path:filename>", methods=["GET"])
def uploaded_image(filename):
    return send_from_directory(
        str(UPLOAD_FOLDER),
        filename,
    )


# ================================================================
# FILE TOO LARGE
# ================================================================

@app.errorhandler(413)
def file_too_large(error):
    return jsonify({
        "success": False,
        "error": "Uploaded file is too large. Maximum size is 100 MB.",
    }), 413


# ================================================================
# GENERIC HTTP ERROR
# ================================================================

@app.errorhandler(500)
def internal_server_error(error):
    print("Flask internal server error:", repr(error))

    return jsonify({
        "success": False,
        "error": "Internal server error.",
    }), 500


# ================================================================
# LOCAL DEVELOPMENT
# ================================================================
#
# Render uses Gunicorn:
#     gunicorn IC:app --bind 0.0.0.0:$PORT --workers 1 --timeout 300
#
# The block below is only for running this file directly on a PC.
# ================================================================

if __name__ == "__main__":
    port = int(os.environ.get("PORT", "5000"))

    print("\n" + "=" * 70)
    print("LUNAR IMAGE CORRESPONDENCE AND REGISTRATION SYSTEM")
    print("=" * 70)
    print("AI: LoFTR + RANSAC + Registration + Quality Analysis")
    print(f"Local server: http://127.0.0.1:{port}")
    print(f"Status: http://127.0.0.1:{port}/status")
    print(f"Analysis API: POST http://127.0.0.1:{port}/analyze")
    print("=" * 70)

    app.run(
        host="0.0.0.0",
        port=port,
        debug=False,
    )
